version: "3.9"

services:
  fastapi:
    build: .
    image: echub:latest
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt #
    depends_on:
      - fastapi
    ports:
      - "443:443"
