services:
  fastapi:
    build: .
    image: echub:latest
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/certs:/etc/nginx/certs
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - fastapi
      - certbot
    ports:
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
