version: "3.9"

services:
  fastapi:
    build: .
    image: echub:latest
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # 本番環境ではコメントイン
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - fastapi
    ports:
      - "443:443"

  # 本番環境ではコメントイン
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email cowki.1999@gmail.com -d echub.site -d www.echub.site --agree-tos
